// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyProject.AppDbContextNameSpace;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251127164659_v6")]
    partial class v6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyProject.Models.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchNo")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("tbl_batch", (string)null);
                });

            modelBuilder.Entity("MyProject.Models.BirdInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchId")
                        .HasColumnType("integer");

                    b.Property<int>("BirdsArrivedCount")
                        .HasColumnType("integer");

                    b.Property<int>("BirdsPerBoxCount")
                        .HasColumnType("integer");

                    b.Property<int>("BoxCount")
                        .HasColumnType("integer");

                    b.Property<int>("BoxMortalityCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisabledBirdCount")
                        .HasColumnType("integer");

                    b.Property<int>("ExcessBirdCount")
                        .HasColumnType("integer");

                    b.Property<int>("HousedBirdCount")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("ShortBirdCount")
                        .HasColumnType("integer");

                    b.Property<int>("TotalBirdCount")
                        .HasColumnType("integer");

                    b.Property<int>("WeakBirdCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BatchId")
                        .IsUnique();

                    b.ToTable("tbl_birdInventory", (string)null);
                });

            modelBuilder.Entity("MyProject.Models.DailyRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchId")
                        .HasColumnType("integer");

                    b.Property<int>("BirdAgeInDays")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FeedConsumedBags")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MortalityCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.ToTable("tbl_dailyRegister", (string)null);
                });

            modelBuilder.Entity("MyProject.Models.FeedInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BagsArrivedCount")
                        .HasColumnType("integer");

                    b.Property<int>("BatchId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DriverPhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.ToTable("tbl_feedInventory", (string)null);
                });

            modelBuilder.Entity("MyProject.Models.FinalReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AdminCost")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AvgBodyWeight")
                        .HasColumnType("numeric");

                    b.Property<int>("BatchId")
                        .HasColumnType("integer");

                    b.Property<decimal>("BirdCost")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BirdRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ChicksCost")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FeedCost")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FeedRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("GrossProductionCost")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MedicineCost")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NetCostPerKg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ProductionCostIncentive")
                        .HasColumnType("numeric");

                    b.Property<decimal>("RearingChargesPerBird")
                        .HasColumnType("numeric");

                    b.Property<decimal>("RearingChargesStd")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("StdCostPerKg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalAmountPayable")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalBags")
                        .HasColumnType("integer");

                    b.Property<int>("TotalBirds")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalBirdsWeight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalFeedKg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalRearingCharges")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalSoldBirds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BatchId")
                        .IsUnique();

                    b.ToTable("tbl_finalReport", (string)null);
                });

            modelBuilder.Entity("MyProject.Models.StockOutEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Birds")
                        .HasColumnType("integer");

                    b.Property<int>("SrNo")
                        .HasColumnType("integer");

                    b.Property<int>("StockOutMasterId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("StockOutMasterId");

                    b.ToTable("tbl_stockOutEntry", (string)null);
                });

            modelBuilder.Entity("MyProject.Models.StockOutMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AvgWeight")
                        .HasColumnType("numeric");

                    b.Property<int>("BatchId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("StockOutNo")
                        .HasColumnType("integer");

                    b.Property<int>("TotalBirds")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalWeight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.ToTable("tbl_stockOut", (string)null);
                });

            modelBuilder.Entity("MyProject.Models.BirdInventory", b =>
                {
                    b.HasOne("MyProject.Models.Batch", "Batch")
                        .WithOne("BirdInventory")
                        .HasForeignKey("MyProject.Models.BirdInventory", "BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("MyProject.Models.DailyRecord", b =>
                {
                    b.HasOne("MyProject.Models.Batch", "Batch")
                        .WithMany("DailyRecords")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("MyProject.Models.FeedInventory", b =>
                {
                    b.HasOne("MyProject.Models.Batch", "Batch")
                        .WithMany("FeedInventories")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("MyProject.Models.FinalReport", b =>
                {
                    b.HasOne("MyProject.Models.Batch", "Batch")
                        .WithOne()
                        .HasForeignKey("MyProject.Models.FinalReport", "BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("MyProject.Models.StockOutEntry", b =>
                {
                    b.HasOne("MyProject.Models.StockOutMaster", "StockOut")
                        .WithMany("Entries")
                        .HasForeignKey("StockOutMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockOut");
                });

            modelBuilder.Entity("MyProject.Models.StockOutMaster", b =>
                {
                    b.HasOne("MyProject.Models.Batch", "Batch")
                        .WithMany("StockOuts")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("MyProject.Models.Batch", b =>
                {
                    b.Navigation("BirdInventory");

                    b.Navigation("DailyRecords");

                    b.Navigation("FeedInventories");

                    b.Navigation("StockOuts");
                });

            modelBuilder.Entity("MyProject.Models.StockOutMaster", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
