// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyProject.AppDbContextNameSpace;

#nullable disable

namespace MyProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251108072439_v2")]
    partial class v2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyProject.Models.BirdInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BirdsArrivedCount")
                        .HasColumnType("int");

                    b.Property<int>("BirdsPerBoxCount")
                        .HasColumnType("int");

                    b.Property<int>("BoxCount")
                        .HasColumnType("int");

                    b.Property<int>("BoxMortalityCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisabledBirdCount")
                        .HasColumnType("int");

                    b.Property<int>("ExcessBirdCount")
                        .HasColumnType("int");

                    b.Property<int>("HousedBirdCount")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalBirdCount")
                        .HasColumnType("int");

                    b.Property<int>("WeakBirdCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tbl_birdInventory", (string)null);
                });

            modelBuilder.Entity("MyProject.Models.DailyRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<int>("BirdAgeInDays")
                        .HasColumnType("int");

                    b.Property<int?>("BirdInventoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("FeedConsumedBags")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MortalityCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BirdInventoryId");

                    b.ToTable("tbl_dailyRegister", (string)null);
                });

            modelBuilder.Entity("MyProject.Models.FeedInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BagsArrivedCount")
                        .HasColumnType("int");

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<int?>("BirdInventoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BirdInventoryId");

                    b.ToTable("tbl_feedInventory", (string)null);
                });

            modelBuilder.Entity("MyProject.Models.DailyRecord", b =>
                {
                    b.HasOne("MyProject.Models.BirdInventory", "BirdInventory")
                        .WithMany("DailyRecords")
                        .HasForeignKey("BirdInventoryId");

                    b.Navigation("BirdInventory");
                });

            modelBuilder.Entity("MyProject.Models.FeedInventory", b =>
                {
                    b.HasOne("MyProject.Models.BirdInventory", "BirdInventory")
                        .WithMany()
                        .HasForeignKey("BirdInventoryId");

                    b.Navigation("BirdInventory");
                });

            modelBuilder.Entity("MyProject.Models.BirdInventory", b =>
                {
                    b.Navigation("DailyRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
