// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using myProject.dbContextNameSpace;

#nullable disable

namespace myProject.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20251016012203_v3")]
    partial class v3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("myProject.Models.BirdInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfBirds")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfBirdsArrived")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfBirdsHoused")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfBox")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfBoxMortality")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfExcess")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfRuns")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfWeaks")
                        .HasColumnType("int");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tbl_birdInventory", (string)null);
                });

            modelBuilder.Entity("myProject.Models.DailyRegister", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("DailyFeedConsume")
                        .HasColumnType("int");

                    b.Property<int>("DailyMortality")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("tbl_dailyReport", (string)null);
                });

            modelBuilder.Entity("myProject.Models.FeedInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DriverPhoneNumber")
                        .HasColumnType("int");

                    b.Property<string>("FeedName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfBagsArrived")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tbl_feedInventory", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
