// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyProject.AppDbContextNameSpace;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyProject.Models.BirdInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchNo")
                        .HasColumnType("integer");

                    b.Property<int>("BirdsArrivedCount")
                        .HasColumnType("integer");

                    b.Property<int>("BirdsPerBoxCount")
                        .HasColumnType("integer");

                    b.Property<int>("BoxCount")
                        .HasColumnType("integer");

                    b.Property<int>("BoxMortalityCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisabledBirdCount")
                        .HasColumnType("integer");

                    b.Property<int>("ExcessBirdCount")
                        .HasColumnType("integer");

                    b.Property<int>("HousedBirdCount")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TotalBirdCount")
                        .HasColumnType("integer");

                    b.Property<int>("WeakBirdCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BatchNo")
                        .IsUnique();

                    b.ToTable("tbl_birdInventory", (string)null);
                });

            modelBuilder.Entity("MyProject.Models.DailyRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchNo")
                        .HasColumnType("integer");

                    b.Property<int>("BirdAgeInDays")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FeedConsumedBags")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MortalityCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BatchNo");

                    b.ToTable("tbl_dailyRegister", (string)null);
                });

            modelBuilder.Entity("MyProject.Models.FeedInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BagsArrivedCount")
                        .HasColumnType("integer");

                    b.Property<int>("BatchNo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DriverPhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BatchNo");

                    b.ToTable("tbl_feedInventory", (string)null);
                });

            modelBuilder.Entity("MyProject.Models.DailyRecord", b =>
                {
                    b.HasOne("MyProject.Models.BirdInventory", "BirdInventory")
                        .WithMany("DailyRecords")
                        .HasForeignKey("BatchNo")
                        .HasPrincipalKey("BatchNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BirdInventory");
                });

            modelBuilder.Entity("MyProject.Models.FeedInventory", b =>
                {
                    b.HasOne("MyProject.Models.BirdInventory", "BirdInventory")
                        .WithMany("FeedInventories")
                        .HasForeignKey("BatchNo")
                        .HasPrincipalKey("BatchNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BirdInventory");
                });

            modelBuilder.Entity("MyProject.Models.BirdInventory", b =>
                {
                    b.Navigation("DailyRecords");

                    b.Navigation("FeedInventories");
                });
#pragma warning restore 612, 618
        }
    }
}
